import Image from "@/components/Image";
import Head from "next/head";
import Stars from "@/components/Stars";

export default function Category({ data }) {
  const games = new Array(20).fill(1);
  const star = () => (
    <svg
      width="20"
      height="20"
      id="__star"
      viewBox="0 0 20 20"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M9.19429 1.51565C9.51142 0.828115 10.4886 0.828117 10.8057 1.51565L12.796 5.83064C12.9253 6.11086 13.1908 6.30379 13.4973 6.34012L18.2161 6.89962C18.968 6.98876 19.2699 7.9181 18.7141 8.43217L15.2253 11.6585C14.9987 11.868 14.8973 12.1802 14.9575 12.4828L15.8835 17.1436C16.0311 17.8862 15.2406 18.4606 14.5799 18.0908L10.4334 15.7698C10.1641 15.619 9.83588 15.619 9.56661 15.7698L5.42013 18.0908C4.75944 18.4606 3.9689 17.8862 4.11646 17.1436L5.04255 12.4828C5.10269 12.1802 5.00126 11.868 4.7747 11.6585L1.28594 8.43217C0.730055 7.9181 1.03202 6.98876 1.7839 6.89962L6.50274 6.34012C6.80917 6.30379 7.07473 6.11085 7.20398 5.83064L9.19429 1.51565Z"
        fill="currentColor"
      />
    </svg>
  );
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="hidden">{star()}</div>
      <div className="container">
        <h1 className="xl:mt-8 xl:mx-8 m-4 text-2xl font-black text-cyan-700">All Games</h1>
        <ul className="grid grid-cols-2 md:grid-cols-4 xl:grid-cols-8 xl:gap-8 gap-4 xl:mt-8 xl:mx-8 xl:mb-12 m-4">
          {games.map((i) => (
            <li key={i}>
              <a href="#">
                <Image
                  src="https://image-component.nextjs.gallery/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fmountains.a2eb1d50.jpg&w=1920&q=75"
                  alt=""
                  width={`100`}
                  height={`100`}
                  className={`object-cover w-full aspect-square rounded-3xl mb-2 shadow-md`}
                />
                <div className="meta mx-2">
                  <div className="font-extrabold text-lg mb-1 text-cyan-700">Transform</div>
                  <div className="font-bold uppercase text-xs mb-2 text-cyan-500">Casual</div>
                  <div>
                    <div className="rating flex mb-2 -ml-1">
                      {Stars((Math.random() * 5).toFixed(1))}
                    </div>
                    <div className="played text-sm text-slate-400">
                      {(Math.random() * 1000).toFixed(1) + `k played`}
                    </div>
                  </div>
                </div>
              </a>
            </li>
          ))}
        </ul>
      </div>
    </>
  );
}
